### ISSUE TITLE
Const?

### ISSUE THREAD

**Issue by mdwagner** [jamiebuilds/babel-plugin-private-underscores#1]
Hello!
Could there be an option to define the symbol as a `const` instead of a `let`? Thank you.

**Comment by jamiebuilds** [comment]
Why

**Comment by mdwagner** [comment]
Because some people (I as well), prefer `const` instead of `let`.

**Comment by mdwagner** [comment]
@jamiebuilds Can I ask why this issue was closed? Do you plan to add this option?
